#!/usr/bin/env python3
"""
rfc_gen.py -- proof -> RFC-text generator (ROADMAP #9).

Turns the machine-checked ceremony-mask proofs into normative RFC-style requirements. For each entry in
rfc_requirements.json it (re)runs Tamarin via the model-tamarin check.py harness, confirms each 'risk'
lemma is REACHABLE (exists-trace verified) and each 'removed_by' lemma HOLDS (all-traces verified), and
emits the requirement backed by those proofs. A requirement whose proofs do not line up is flagged
UNVERIFIED rather than emitted as fact -- the RFC text is only ever as strong as the proofs behind it.

Usage (from the repo root):
    python3 tamarin_model/tools/rfc_gen.py            # verify proofs, write tamarin_model/RFC_GUIDANCE.md
    python3 tamarin_model/tools/rfc_gen.py --no-verify # trust manifest, just render (fast)
"""
import json, re, subprocess, sys, pathlib

HERE = pathlib.Path(__file__).resolve()
REPO = HERE.parents[2]                      # tamarin_model/tools/rfc_gen.py -> repo root
CHECK = REPO / ".claude/skills/model-tamarin/check.py"
MANIFEST = HERE.parent / "rfc_requirements.json"
OUT = REPO / "tamarin_model/RFC_GUIDANCE.md"

VERDICT_RE = re.compile(r"^\s*(?:ok|fail)\s+(\S+)\s+(exists-trace|all-traces)\s+(verified|falsified)")


def prove(profile, cache):
    """Run check.py --prove on a profile; return {lemma: (kind, verdict)}. Cached per profile."""
    if profile in cache:
        return cache[profile]
    res = subprocess.run([sys.executable, str(CHECK), "--prove", str(REPO / profile)],
                         capture_output=True, text=True)
    verdicts = {}
    for line in (res.stdout + res.stderr).splitlines():
        m = VERDICT_RE.match(line)
        if m:
            verdicts[m.group(1)] = (m.group(2), m.group(3))
    cache[profile] = verdicts
    return verdicts


def check_ref(ref, kind_expected, cache):
    """kind_expected: 'reachable' (exists-trace verified) or 'holds' (all-traces verified)."""
    v = prove(ref["profile"], cache).get(ref["lemma"])
    if v is None:
        return False, "lemma not found / profile failed"
    kind, verdict = v
    if verdict != "verified":
        return False, f"{verdict}"
    if kind_expected == "reachable" and kind != "exists-trace":
        return False, f"expected exists-trace, got {kind}"
    if kind_expected == "holds" and kind != "all-traces":
        return False, f"expected all-traces, got {kind}"
    return True, kind


def main():
    verify = "--no-verify" not in sys.argv
    man = json.loads(MANIFEST.read_text())
    cache = {}
    out = ["# " + man["title"], "",
           "> Generated by `tamarin_model/tools/rfc_gen.py` from machine-checked proofs"
           + ("" if verify else " (manifest rendered WITHOUT re-verification)") + ".", "",
           man["intro"], ""]
    n_ok = 0
    for r in man["requirements"]:
        backing, ok = [], True
        if verify:
            for vref in r["vulnerable"]:
                good, info = check_ref(vref, "reachable", cache)
                ok &= good
                backing.append((f"`{vref['lemma']}`", vref["profile"].split("/")[-1],
                                "risk reachable" if good else f"UNVERIFIED ({info})"))
            rb = r.get("removed_by")
            if rb:
                good, info = check_ref(rb, "holds", cache)
                ok &= good
                backing.append((f"`{rb['lemma']}`", rb["profile"].split("/")[-1],
                                "risk removed" if good else f"UNVERIFIED ({info})"))
        status = "PROVEN" if (ok or not verify) else "UNVERIFIED"
        if ok or not verify:
            n_ok += 1
        out += [f"## {r['id']} — {r['title']}  ·  _{status}_", "",
                f"**Risk.** {r['risk_text']}", ""]
        rb = r.get("removed_by")
        if rb:
            out.append(f"**Lever.** {rb['lever']}.")
            out.append("")
        out += [f"**Requirement.** {r['requirement']}", ""]
        if verify:
            out.append("**Proof backing.**")
            for lemma, prof, note in backing:
                out.append(f"- {lemma} ({prof}) — {note}")
            out.append("")
    out.insert(5, f"**{n_ok}/{len(man['requirements'])} requirements "
                  + ("proven" if verify else "rendered") + ".**\n")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(REPO)} — {n_ok}/{len(man['requirements'])} "
          + ("proven" if verify else "rendered"))
    return 0 if n_ok == len(man["requirements"]) else 1


if __name__ == "__main__":
    sys.exit(main())
